src/main/java/br/com/rustic/entities/Beer.java
package br.com.rustic.entities;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
@Table( name = "CERVEJA" )
public class Beer extends BaseEntity implements Serializable {

	private static final long serialVersionUID = 2948830986309645512L;

	@Id
	@GeneratedValue( strategy = GenerationType.IDENTITY )
	@Column( name = "PK_ID_CERVEJA" )
	private Integer id;

	@NotNull
	@Column( name = "DC_NOME" )
	private String name;

	@NotNull
	@Column( name = "DC_VOLUME" )
	private String volume;

	@NotNull
	@Column( name = "DC_TEOR_ALCOOLICO" )
	private String alcoholicGraduation;

	@OneToOne( fetch = FetchType.EAGER )
	@JoinColumn( name = "FK_ID_ESTILO" )
	private Style style;

	@NotNull
	@Column( name = "DC_PRECO" )
	private String price;

	@Column( name = "DC_CERVEJARIA" )
	private String brewery;

	@Column( name = "DC_PAIS_ORIGEM" )
	private String countryOrigin;

	@Column( name = "DC_TEMPERATURA" )
	private String temperature;

	@OneToOne( fetch = FetchType.EAGER )
	@JoinColumn( name = "FK_ID_TIPO_COPO" )
	private CupType cupType;

	@Column( name = "DC_CODIGO" )
	private String code;

	@Column( name = "DC_DESCRICAO" )
	@Size( max = 1000 )
	private String description;

	@Column( name = "DC_HARMONIZACAO" )
	@Size( max = 1000 )
	private String harmonization;

	@Column( name = "FL_EM_ESTOQUE" )
	private Boolean inStock;

	@Column( name = "DC_AMARGOR" )
	private String bitterness;

	@OneToOne( fetch = FetchType.EAGER, cascade = CascadeType.ALL )
	@NotNull
	@JoinColumn( name = "FK_ID_IMAGEM_CERVEJA" )
	private UploadFile imageBeer;

	@OneToOne( fetch = FetchType.EAGER, cascade = CascadeType.ALL )
	@JoinColumn( name = "FK_ID_AVALIACAO" )
	private Rate rate;

	@Override
	public Integer getId() {
		return id;
	}

	@Override
	public void setId( Integer id ) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName( String name ) {
		this.name = name;
	}

	public String getVolume() {
		return volume;
	}

	public void setVolume( String volume ) {
		this.volume = volume;
	}

	public String getAlcoholicGraduation() {
		return alcoholicGraduation;
	}

	public void setAlcoholicGraduation( String alcoholicGraduation ) {
		this.alcoholicGraduation = alcoholicGraduation;
	}

	public Style getStyle() {
		return style;
	}

	public void setStyle( Style style ) {
		this.style = style;
	}

	public String getBrewery() {
		return brewery;
	}

	public void setBrewery( String brewery ) {
		this.brewery = brewery;
	}

	public String getCountryOrigin() {
		return countryOrigin;
	}

	public void setCountryOrigin( String countryOrigin ) {
		this.countryOrigin = countryOrigin;
	}

	public String getTemperature() {
		return temperature;
	}

	public void setTemperature( String temperature ) {
		this.temperature = temperature;
	}

	public CupType getCupType() {
		return cupType;
	}

	public void setCupType( CupType cupType ) {
		this.cupType = cupType;
	}

	public String getCode() {
		return code;
	}

	public void setCode( String code ) {
		this.code = code;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription( String description ) {
		this.description = description;
	}

	public String getHarmonization() {
		return harmonization;
	}

	public void setHarmonization( String harmonization ) {
		this.harmonization = harmonization;
	}

	public UploadFile getImageBeer() {
		return imageBeer;
	}

	public void setImageBeer( UploadFile imageBeer ) {
		this.imageBeer = imageBeer;
	}

	public Boolean getInStock() {
		return inStock;
	}

	public void setInStock( Boolean inStock ) {
		this.inStock = inStock;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice( String price ) {
		this.price = price;
	}

	public Rate getRate() {
		return rate;
	}

	public void setRate( Rate rate ) {
		this.rate = rate;
	}

	public String getBitterness() {
		return bitterness;
	}

	public void setBitterness( String bitterness ) {
		this.bitterness = bitterness;
	}

}

src/main/java/br/com/rustic/controllers/BeerController.java
package br.com.rustic.controllers;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;

import br.com.rustic.entities.Beer;
import br.com.rustic.entities.CupType;
import br.com.rustic.entities.Style;
import br.com.rustic.entities.UploadFile;
import br.com.rustic.services.BeerService;
import br.com.rustic.services.CupTypeService;
import br.com.rustic.services.StyleService;

@Named
@Scope( "view" )
public class BeerController implements Serializable {

	private static final long serialVersionUID = -3303391814185815178L;

	@Autowired
	private BeerService beerService;

	@Autowired
	private StyleService styleService;

	@Autowired
	private CupTypeService cupTypeService;

	@Autowired
	private ImageController imageController;

	private Beer entity;

	private Integer startTemperature;
	private Integer endTemperature;

	@PostConstruct
	public void init() {
		clean();
	}

	public void clean() {
		entity = new Beer();
		entity.setInStock( true );
		startTemperature = 0;
		endTemperature = 0;
	}

	public void create() {

		if ( entity.getImageBeer() == null ) {
			FacesContext.getCurrentInstance().addMessage( null, new FacesMessage( FacesMessage.SEVERITY_ERROR, "Imagem é obrigatório.", "Imagem é obrigatório." ) );
			return;
		}

		if ( startTemperature != 0 && endTemperature != 0 ) {
			if ( startTemperature == endTemperature ) {
				entity.setTemperature( String.format( "%d °C", startTemperature ) );
			} else {
				entity.setTemperature( String.format( "%d-%d °C", startTemperature, endTemperature ) );
			}
		}
		beerService.save( entity );
		FacesContext.getCurrentInstance().addMessage( null, new FacesMessage( "Cadastro realizado com sucesso" ) );
		clean();
	}

	public Beer getEntity() {
		return entity;
	}

	public void setEntity( Beer entity ) {
		this.entity = entity;
	}

	public List<Style> autocompleteStyle( String query ) {
		return styleService.autoCompleteStyle( query );
	}

	public List<CupType> autocompleteCupType( String query ) {
		return cupTypeService.autoCompleteCupType( query );
	}

	public List<String> autocompleteBitterness() {
		List<String> bitterness = new ArrayList<String>();
		bitterness.add( "Muito suave" );
		bitterness.add( "Suave" );
		bitterness.add( "Regular" );
		bitterness.add( "Forte" );
		bitterness.add( "Muito forte" );
		return bitterness;
	}

	public void handleFileUpload( FileUploadEvent event ) throws IOException, InterruptedException {
		UploadedFile file = event.getFile();

		if ( !Arrays.asList( "jpg", "jpe", "jpge", "png" ).contains( getExtension( file.getFileName() ).toLowerCase() ) ) {
			FacesContext.getCurrentInstance().addMessage( null, new FacesMessage( FacesMessage.SEVERITY_ERROR, "Somente são aceitas imagens do tipo JPG, JPE, JPGE, PNG.", "Somente são aceitas imagens do tipo JPG, JPE, JPGE, PNG." ) );
			return;
		}

		UploadFile imageBeer = new UploadFile();
		imageBeer.setName( file.getFileName() );
		imageBeer.setExtension( getExtension( file.getFileName() ) );
		imageBeer.setPath( null );
		imageBeer.setFileContent( file.getContents() );

		entity.setImageBeer( imageBeer );
		imageController.setImage( file );
	}

	private String getExtension( String name ) {
		return name.replaceAll( ".+\\.(.+)", "$1" );
	}

	public Integer getStartTemperature() {
		return startTemperature;
	}

	public void setStartTemperature( Integer startTemperature ) {
		this.startTemperature = startTemperature;
	}

	public Integer getEndTemperature() {
		return endTemperature;
	}

	public void setEndTemperature( Integer endTemperature ) {
		this.endTemperature = endTemperature;
	}

}

src/main/java/br/com/rustic/controllers/ImageController.java
package br.com.rustic.controllers;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.InputStream;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;
import javax.inject.Named;

import org.apache.commons.io.FileUtils;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;
import org.springframework.context.annotation.Scope;
import org.springframework.util.StringUtils;

@Named
@Scope( "session" )
public class ImageController {

	private UploadedFile image;

	public StreamedContent getImageContent() {
		try {
			String imageBeerPath = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get( "imageBeerPath" );

			ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
			InputStream isDefault = externalContext.getResourceAsStream( "/resources/images/rustic_logo.jpg" );

			FacesContext context = FacesContext.getCurrentInstance();
			if ( context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE ) {
				return new DefaultStreamedContent( isDefault );
			}
			if ( image != null ) {
				InputStream is = new ByteArrayInputStream( image.getContents() );
				this.image = null;
				return new DefaultStreamedContent( is );
			} else if ( !StringUtils.isEmpty( imageBeerPath ) ) {
				File imageBeer = new File( imageBeerPath );
				InputStream is = new ByteArrayInputStream( FileUtils.readFileToByteArray( imageBeer ) );
				return new DefaultStreamedContent( is );
			} else {
				return new DefaultStreamedContent( isDefault );
			}
		} catch ( Exception e ) {
			return new DefaultStreamedContent();
		}
	}

	public UploadedFile getImage() {
		return image;
	}

	public void setImage( UploadedFile image ) {
		this.image = image;
	}

}

src/main/java/br/com/rustic/controllers/search/BeerSearchController.java
package br.com.rustic.controllers.search;

import java.util.Arrays;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import org.primefaces.component.tabview.Tab;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.data.domain.Page;
import org.springframework.util.StringUtils;

import br.com.rustic.controllers.ImageController;
import br.com.rustic.entities.Beer;
import br.com.rustic.entities.UploadFile;
import br.com.rustic.services.BeerService;

@Named
@Scope( "view" )
public class BeerSearchController extends BaseSearchController<Beer> {

	private static final long serialVersionUID = -2718835236454340861L;

	@Autowired
	private BeerService beerService;

	@Autowired
	private ImageController imageController;

	private transient Tab searchTab;
	private String searchValue;
	private Integer startTemperature;
	private Integer endTemperature;

	public BeerSearchController() {
		super( Beer.class );
	}

	@PostConstruct
	public void init() {
		this.setEditEntity( new Beer() );
		this.setRemoveEntity( new Beer() );
		clean();
	}

	public void clean() {
		this.setSearchEntity( new Beer() );
		this.searchValue = null;
		this.startTemperature = 0;
		this.endTemperature = 0;
	}

	public void handleFileUpload( FileUploadEvent event ) {
		UploadedFile file = event.getFile();

		if ( !Arrays.asList( "jpg", "jpe", "jpge", "png" ).contains( getExtension( file.getFileName() ).toLowerCase() ) ) {
			FacesContext.getCurrentInstance().addMessage( null, new FacesMessage( FacesMessage.SEVERITY_ERROR, "Somente são aceitas imagens do tipo JPG, JPE, JPGE, PNG.", "Somente são aceitas imagens do tipo JPG, JPE, JPGE, PNG." ) );
			return;
		}

		UploadFile imageBeer = new UploadFile();
		imageBeer.setName( file.getFileName() );
		imageBeer.setExtension( getExtension( file.getFileName() ) );
		imageBeer.setPath( null );
		imageBeer.setFileContent( file.getContents() );

		getEditEntity().setImageBeer( imageBeer );

		imageController.setImage( file );
	}

	private String getExtension( String name ) {
		return name.replaceAll( ".+\\.(.+)", "$1" );
	}

	@Override
	public void edit() {
		startTemperature = 0;
		endTemperature = 0;
		if ( !StringUtils.isEmpty( getEditEntity().getTemperature() ) ) {
			String[] temperature = getEditEntity().getTemperature().split( "-" );
			if ( temperature.length > 1 ) {
				startTemperature = Integer.valueOf( temperature[0].trim() );
				endTemperature = Integer.valueOf( temperature[1].replace( "°C", "" ).trim() );
			} else {
				startTemperature = Integer.valueOf( temperature[0].replace( "°C", "" ).trim() );
				endTemperature = Integer.valueOf( temperature[0].replace( "°C", "" ).trim() );
			}
		}
		super.edit();
	}

	public void remove() {
		beerService.remove( getRemoveEntity() );
		FacesContext.getCurrentInstance().addMessage( null, new FacesMessage( "Cerveja removida com sucesso" ) );
	}

	public void update() {
		if ( startTemperature != 0 && endTemperature != 0 ) {
			if ( startTemperature == endTemperature ) {
				getEditEntity().setTemperature( String.format( "%d °C", startTemperature ) );
			} else {
				getEditEntity().setTemperature( String.format( "%d-%d °C", startTemperature, endTemperature ) );
			}
		}
		beerService.save( getEditEntity() );
		closeTab( getEditTab() );
		FacesContext.getCurrentInstance().addMessage( null, new FacesMessage( "Cerveja atualizada com sucesso" ) );
	}

	public Tab getSearchTab() {
		return searchTab;
	}

	public void setSearchTab( Tab searchTab ) {
		this.searchTab = searchTab;
	}

	@Override
	protected Page<Beer> getList() {
		return beerService.findAll( searchValue );
	}

	public String getSearchValue() {
		return searchValue;
	}

	public void setSearchValue( String searchValue ) {
		this.searchValue = searchValue;
	}

	public Integer getStartTemperature() {
		return startTemperature;
	}

	public void setStartTemperature( Integer startTemperature ) {
		this.startTemperature = startTemperature;
	}

	public Integer getEndTemperature() {
		return endTemperature;
	}

	public void setEndTemperature( Integer endTemperature ) {
		this.endTemperature = endTemperature;
	}
}

src/main/webapp/views/admin/beer/BeerCadastre.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:x="http://java.sun.com/jsf/composite/components"
	xmlns:p="http://primefaces.org/ui"
	xmlns:m="http://code.google.com/p/gmaps4jsf/"
	template="/views/admin/index.xhtml">

	<ui:define name="content">
		<h:form id="createForm">
			<section>
				<div>
					<ol class="breadcrumb">
						<li><i class="fa fa-beer"></i> Cervejas</li>
						<li class="active">Cadastro</li>
					</ol>
				</div>
			</section>

			<p:panel id="dataPanel" header="Dados da Cerveja" toggleable="true" styleClass="ui-grid ui-grid-responsive">

				<div class="ui-fluid">
					<p:outputLabel value="Imagem" styleClass="ui-grid-col-1">
						<span class="ui-outputlabel-rfi">*</span>
					</p:outputLabel>
					<p:fileUpload id="uploader" label="Selecionar" fileUploadListener="#{beerController.handleFileUpload}" styleClass="ui-grid-col-2"
							auto="true" mode="advanced" dragDropSupport="false" update="imageUploaded"/>
				</div>
				
				<div class="ui-grid-row">
					<p:graphicImage id="imageUploaded" value="#{imageController.imageContent}" styleClass="image-uploaded img-thumbnail" cache="false"/>
				</div>

				<div class="ui-grid-row">
					<p:outputLabel for="name" value="Nome" class="ui-grid-col-1" />
					<p:inputText id="name" maxlength="50" value="#{beerController.entity.name}" required="true" class="ui-grid-col-3"/>

					<p:outputLabel for="price" value="Preço" class="ui-grid-col-1" />
					<pe:inputNumber id="price" value="#{beerController.entity.price}" maxValue="9999" required="true" styleClass="ui-grid-col-2"
									symbolPosition="left" symbol=" R$" thousandSeparator="." decimalPlaces="2" decimalSeparator="," />
					
					
					<p:outputLabel for="volume" value="Volume" class="ui-grid-col-1" />
					<pe:inputNumber id="volume" value="#{beerController.entity.volume}" maxValue="9999" required="true" styleClass="ui-grid-col-1"
									symbolPosition="left" symbol="ml" thousandSeparator="" decimalPlaces="0" decimalSeparator="" />
					
					<p:outputLabel for="alcoholicGraduation" value="Grad. Alcoólica" class="ui-grid-col-2" />
					<pe:inputNumber id="alcoholicGraduation" value="#{beerController.entity.alcoholicGraduation}" maxValue="99" decimalPlaces="1" symbol="% ABV" symbolPosition="right" styleClass="ui-grid-col-1"/>  
				</div>
				
				<div class="ui-grid-row">
					<p:outputLabel for="styleAutoComplete" value="Estilo" class="ui-grid-col-1" />
					<div class="ui-grid-col-3">
						<p:autoComplete id="styleAutoComplete" dropdown="true"	value="#{beerController.entity.style}"
									completeMethod="#{beerController.autocompleteStyle}" var="var" itemLabel="#{var.style}" itemValue="#{var}"
									forceSelection="true" minQueryLength=""	label="Estilo" scrollHeight="200"
									converter="autocompleteConverter" required="true">
						</p:autoComplete>
					</div>
					
					<p:outputLabel for="bitternessSelect" value="Amargor" class="ui-grid-col-1" />
					<div class="ui-grid-col-3">
						<p:selectOneMenu id="bitternessSelect" value="#{beerController.entity.bitterness}" label="Amargor" required="false">
							<f:selectItem itemLabel="" itemValue="#{null}" />
							<f:selectItems value="#{beerController.autocompleteBitterness()}" var="var" itemLabel="#{var}" itemValue="#{var}" />
						</p:selectOneMenu>
					</div>
					
					<div></div>
					<p:outputLabel for="brewery" value="Cervejaria" class="ui-grid-col-1" />
					<p:inputText id="brewery" maxlength="50" value="#{beerController.entity.brewery}" required="false" class="ui-grid-col-2" />
			
					<p:outputLabel for="countryOrigin" value="País" class="ui-grid-col-1" />
					<p:inputText id="countryOrigin" maxlength="50" value="#{beerController.entity.countryOrigin}" required="false" class="ui-grid-col-2" />
				</div>
				
				<div class="ui-grid-row">
					<p:outputLabel value="Temperatura de Serviço" class="ui-grid-col-2" />
					<div class="ui-grid-col-1">
						<p:spinner id="startTemperature" value="#{beerController.startTemperature}" maxlength="3" required="false"/>
					</div>
					<div style="text-align: center;font-weight:bold;padding-top:4px;">a</div>
					<div class="ui-grid-col-1">
						<p:spinner id="endTemperature" value="#{beerController.endTemperature}" maxlength="3" required="false"/>
					</div>	
					
					<p:outputLabel for="cupTypeAutoComplete" value="Tipo de Copo" class="ui-grid-col-2" />
					<div class="ui-grid-col-3">
						<p:autoComplete id="cupTypeAutoComplete" dropdown="true"	value="#{beerController.entity.cupType}"
									completeMethod="#{beerController.autocompleteCupType}" var="var" itemLabel="#{var.cupType}" itemValue="#{var}"
									forceSelection="true" minQueryLength=""	label="Estilo" scrollHeight="200"
									converter="autocompleteConverter" required="false">
						</p:autoComplete>
					</div>
					
					<p:outputLabel for="code" value="Código" class="ui-grid-col-1" />
					<p:inputText id="code" maxlength="50" value="#{beerController.entity.code}" required="false" class="ui-grid-col-2" />
				</div>
				
				<div class="ui-grid-row">
					<p:outputLabel for="description" value="Descrição" class="ui-grid-col-2" />
					<p:inputTextarea id="description"  rows="3" value="#{beerController.entity.description}" required="false" class="ui-grid-col-10" />
				</div>
				
				<div class="ui-grid-row">
					<p:outputLabel for="harmonization" value="Harmonização" class="ui-grid-col-2" />
					<p:inputTextarea id="harmonization"  rows="3" value="#{beerController.entity.harmonization}" required="false" class="ui-grid-col-10" />
				</div>
				
				<div class="ui-grid-row">
					<p:outputLabel for="inStock" value="Em estoque"	class="ui-grid-col-2" />
					<p:selectOneRadio id="inStock"	value="#{beerController.entity.inStock}" class="ui-grid-col-3" required="true">
						<f:selectItem itemLabel="Não" itemValue="#{false}" />
						<f:selectItem itemLabel="Sim" itemValue="#{true}" />
					</p:selectOneRadio>
				</div>

				<div class="buttonsGroup">
					<p:commandButton id="createCommandButton" icon="ui-icon-disk" value="Cadastrar" action="#{beerController.create}" process="@form" update="@form" />
					<p:commandButton id="cleanCommandButton" icon="ui-icon-arrowrefresh-1-w" value="Limpar" action="#{beerController.clean}" process="@this" update="@form">
						<p:resetInput target=":createForm"></p:resetInput>
					</p:commandButton>
				</div>
			</p:panel>
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/views/admin/beer/BeerManagement.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:x="http://java.sun.com/jsf/composite/components" template="/views/admin/index.xhtml">

	<ui:define name="content">

		<p:tabView id="beerTabView" widgetVar="beerTabs" dynamic="false">
		
			<p:ajax event="tabClose" update="beerTabView" listener="#{beerSearchController.onTabClose}" process="@all" />
			
			<p:tab id="searchTab" binding="#{beerSearchController.searchTab}" title="Consultar Cervejas">
				<section>
					<div>
						<ol class="breadcrumb">
							<li><i class="fa fa-beer"></i> Cervejas</li>
							<li class="active">Consultar</li>
						</ol>
					</div>
				</section>
				
				<ui:include src="BeerSearch.xhtml" />
			</p:tab>
			
			<p:tab id="editTab" binding="#{beerSearchController.editTab}" title="Editar Cerveja" rendered="false" closable="true">
				<section>
					<div>
						<ol class="breadcrumb">
							<li><i class="fa fa-beer"></i> Cervejas</li>
							<li class="active">Editar</li>
						</ol>
					</div>
				</section>
				<ui:include src="BeerEdit.xhtml" />
			</p:tab>

		</p:tabView>
	</ui:define>
</ui:composition>