src/main/java/br/com/rustic/controllers/LoginController.java
package br.com.rustic.controllers;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.AuthenticationException;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.web.authentication.session.SessionAuthenticationException;
import org.springframework.security.web.authentication.session.SessionAuthenticationStrategy;

import br.com.rustic.config.spring.security.AdminAuthenticationToken;
import br.com.rustic.entities.User;
import br.com.rustic.services.UserService;

@Named
@Scope( "session" )
public class LoginController {

	@Autowired
	private AuthenticationManager authenticationManager;

	@Autowired
	private SessionAuthenticationStrategy sessionAuthenticationStrategy;

	@Autowired
	private UserService userService;

	private String username;
	private String password;

	public String login() {
		FacesContext context = FacesContext.getCurrentInstance();

		try {
			Authentication authentication = new AdminAuthenticationToken( getUsername(), getPassword() );

			Authentication result = authenticationManager.authenticate( authentication );
			SecurityContextHolder.getContext().setAuthentication( result );

			HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
			HttpServletResponse response = (HttpServletResponse) context.getExternalContext().getResponse();
			sessionAuthenticationStrategy.onAuthentication( result, request, response );

		} catch ( SessionAuthenticationException e ) {
			e.printStackTrace();
			SecurityContextHolder.getContext().getAuthentication().setAuthenticated( false );
			context.addMessage( null, new FacesMessage( FacesMessage.SEVERITY_ERROR, "Usuário já autenticado.", "Usuário já autenticado." ) );
			return null;
		} catch ( AuthenticationException e ) {
			e.printStackTrace();
			context.addMessage( null, new FacesMessage( FacesMessage.SEVERITY_ERROR, e.getMessage(), e.getMessage() ) );
			password = null;
			return null;
		}
		return "/views/admin/index?faces-redirect=true";
	}

	public String getUsername() {
		return username;
	}

	public void setUsername( String userName ) {
		this.username = userName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword( String password ) {
		this.password = password;
	}

	public User getCurrentUser() {
		return userService.loadCurrentUser();
	}

}

src/main/webapp/views/admin/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<meta charset="utf-8"></meta>
	<meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
	<meta name="viewport" content="width=device-width, initial-scale=1"></meta>

	<title>Admin Rustic</title>
	<link rel="shortcut icon" href="#{request.contextPath}/resources/images/rustic_icon.png"></link>
	<!-- Bootstrap core CSS -->

	<link rel="stylesheet" type="text/css"
		href="#{request.contextPath}/resources/js/bootstrap/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css"
		href="#{request.contextPath}/resources/dist/css/AdminLTE.min.css" />
	<link rel="stylesheet" type="text/css"
		href="#{request.contextPath}/resources/dist/css/skins/skin-red.min.css" />
	<link rel="stylesheet"
		href="#{request.contextPath}/resources/css/layout.css" />
	<link rel="stylesheet"
		href="#{request.contextPath}/resources/css/grid.css" />
	<link rel="stylesheet"
		href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
	<link rel="stylesheet"
		href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />

	<h:outputScript library="primefaces" name="jquery/jquery.js" />
	<h:outputScript name="js/bootstrap/js/bootstrap.min.js" />
	<h:outputScript name="dist/js/app.min.js" />

</h:head>
<h:body class="hold-transition skin-red sidebar-mini">

	<div class="wrapper">
		<!-- Main Header -->
		<header class="main-header">

			<!-- Logo -->
			<a href="#{request.contextPath}/views/admin/index.xhtml" class="logo"> <!-- mini logo for sidebar mini 50x50 pixels -->
				<span class="logo-mini"><b>A</b>R</span> <!-- logo for regular state and mobile devices -->
				<span class="logo-lg"><b>Admin</b>Rustic</span>
			</a>

			<!-- Header Navbar -->
			<nav class="navbar navbar-static-top" role="navigation">
				<!-- Sidebar toggle button-->
				<a href="#" class="sidebar-toggle" data-toggle="offcanvas"
					role="button"> <span class="sr-only">Toggle navigation</span>
				</a>
				<!-- Navbar Right Menu -->
				<div class="navbar-custom-menu">
					<ul class="nav navbar-nav">
						<!-- User Account Menu -->
						<li class="dropdown user user-menu"><a
							class="dropdown-toggle" data-toggle="dropdown" href="#"> <i
								class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
						</a>
							<ul class="dropdown-menu dropdown-user">
							</ul>
							<ul class="dropdown-menu">
								<!-- The user image in the menu -->
								<li class="user-header">
									<p>#{loginController.currentUser.name} - Admin</p>
								</li>
								<!-- Menu Footer-->
								<li class="user-footer">
									<div class="pull-left">
										<a href="#{request.contextPath}/views/admin/user/userEdit.xhtml" class="btn btn-default btn-flat">Perfil</a>
									</div>
									<div class="pull-right">
										<a href="#{request.contextPath}/views/admin/logout" class="btn btn-default btn-flat">Logout</a>
									</div>
								</li>
							</ul></li>
					</ul>
				</div>
			</nav>
		</header>
		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section id="sideBar" class="sidebar">

				<!-- Sidebar Menu -->
				<ul id="sideBarMenu" class="sidebar-menu">
					<li class="header">MENU</li>
					<!-- Optionally, you can add icons to the links -->
					<li class=""><a href="#{request.contextPath}/views/admin/index.xhtml"><i
							class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
					<li class="treeview"><a href=""><i class="fa fa-beer"></i>
							<span>Cervejas</span> <i class="fa fa-angle-left pull-right"></i></a>
						<ul class="treeview-menu">
							<li><a href="#{request.contextPath}/views/admin/beer/BeerCadastre.xhtml">Cadastro</a></li>
							<li><a href="#{request.contextPath}/views/admin/beer/BeerManagement.xhtml">Gestão</a></li>
							<li><a href="#{request.contextPath}/views/public/beerMenu.xhtml">Carta de Cervejas</a></li>
						</ul></li>
				</ul>
				<!-- /.sidebar-menu -->
			</section>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->

			<!-- Main content -->
			<section class="content">
				<div class="grid-responsive">
					<p:messages id="messagesSystem" closable="true" autoUpdate="true"
						severity="error, fatal, warn, info" showDetail="true" showSummary="false" />
<!-- 					<p:ajaxStatus oncomplete="setTimeout(function() { $('.ui-messages').slideUp(); }, 30000)" /> -->
				</div>
				<!-- Your Page Content Here -->
				<ui:insert name="content" />

			</section>
			<!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<!-- Main Footer -->
		<footer class="main-footer">
			<div class="pull-right hidden-xs">
				<strong>Versão 1.0</strong>
			</div>
			<strong>Rustic Hamburgueria © 2016</strong>
		</footer>
		
	</div>
	<!-- ./wrapper -->
	
	<!-- 12*60*1000 -->
	<p:idleMonitor timeout="1680000" onidle="PF('idleDialog').show();">
	</p:idleMonitor>

	<p:dialog header="Sessão Expirada" resizable="false" closable="false" widgetVar="idleDialog" modal="true" width="300" style="text-align: center">
		<br />
		<br />
		Sua sessão expirou devido à inatividade.<br />
		<a href="#{request.contextPath}/admin/login.xhtml" style="color: #005580; text-decoration: underline;">Clique aqui para entrar novamente</a>.
		<br />
		<br />
		<br />
	</p:dialog>
	
	
	<script type="text/javascript">
	$(function() {
	     var pgurl = window.location.href.substr(window.location.href.lastIndexOf("/")+1);
	     $("#sideBar ul li a").each(function(){
		 	var href = $(this).attr("href").substr($(this).attr("href").lastIndexOf("/")+1);
	        if(href == pgurl){
	      		$(this).parents('li').addClass('active');
		        $(this).parent().addClass("active");
	        }
	     })
	});
	</script>

</h:body>

</html>

src/main/webapp/views/admin/login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<link rel="shortcut icon"
		href="#{request.contextPath}/resources/images/rustic_icon.png"></link>

	<link rel="stylesheet" type="text/css"
		href="#{request.contextPath}/resources/js/bootstrap/css/bootstrap.min.css" />

	<link rel="stylesheet" type="text/css"
		href="#{request.contextPath}/resources/dist/css/skins/skin-red.min.css" />

	<link rel="stylesheet"
		href="#{request.contextPath}/resources/css/layout.css" />
	<link rel="stylesheet"
		href="#{request.contextPath}/resources/css/grid.css" />

</h:head>

<h:body class="hold-transition skin-red sidebar-mini">
	<h:form id="formLogin">
			<div class="row-login">
				<div class="col-md-4 col-md-offset-4">
					<div class="login-panel panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">AdminRustic - Identificação do Usuário</h3>
						</div>
						<div class="panel-body">
							<div class="form-group">
								<p:inputText id="username" placeholder="Usuário" value="#{loginController.username}" styleClass="form-control" autocomplete="off"/>
							</div>
							<div class="form-group">
								<p:password id="password" placeholder="Senha" value="#{loginController.password}" feedback="false" styleClass="form-control" autocomplete="off"/>
							</div>
							
							<h:messages id="messages" layout="table" class="grid_24"
								style="color:red; font-weight:bold; text-align: center;" />
							<p:commandButton id="loginButton" action="#{loginController.login}" value="Login" update="messages password" styleClass="btn btn-lg btn-success btn-block" />
						</div>
					</div>
				</div>
			</div>
	</h:form>
</h:body>

</html>